version: '3.8'
services:
  todoapp-udemy:
    build: ./ToDoApp
    volumes:
      - ./ToDoApp:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    command: ["npm", "start"]
    ports:
      - '3001:3000'
    stdin_open: true
    tty: true
